# Generated by Django 5.1.5 on 2025-01-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Converted', 'Converted'), ('Rejected', 'Rejected')], default='New', max_length=20)),
                ('source', models.CharField(choices=[('Online', 'Online'), ('Referral', 'Referral'), ('Event', 'Event'), ('Advertisement', 'Advertisement')], default='Online', max_length=20)),
            ],
        ),
    ]
